### ISSUE TITLE
Consider having the 2% community tax + lower minimum proposal deposit

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-core#186] opened 2021-07-13 01:57 UTC
We may need to change the following two parameters via a ParameterChangeProposal.

## Community Tax

In the Cosmos Hub, the community tax is 2%: https://github.com/cosmos/cosmos/blob/master/VALIDATORS_FAQ.md#how-are-fees-distributed.
We have set it to 0% so far, but we should consider changing it to 2%.

For that,
  - Let's research how the community tax has been used in other chains. It would be helpful for us to write a proposal for increasing the community tax ratio.
  - Let's make a governance rehearsal which consumes the community tax.

## Min Proposal Deposit
As discussed in https://www.mintscan.io/cosmos/proposals/47, I think the minDepositTokens 100,000 MED is too high (considering the current market price). Because most of Cosmos Hub validators have agreed on the 64 ATOM of minDepositTokens (1,000,000 KRW approximately), it may be good to set our minDepositTokens to 10,000 MED.

**Comment by youngjoon-lee** [comment] 2021-07-13 02:53
As discussed in https://www.mintscan.io/cosmos/proposals/47, I think the `minDepositTokens` 100,000 MED is too high (considering the current market price). Because most of Cosmos Hub validators have agreed on the 64 ATOM of minDepositTokens (1,000,000 KRW approximately), it may be good to set our minDepositTokens to 10,000 MED.

**Comment by gyuguen** [comment] 2021-09-27 05:13
I looked up how to use community pools in Cosmos.

### Rejected
- Among them, agendas on attracting investment or providing liquidity pools (Osmosis) were rejected.

### Passed proposal
- Improved function.(Governance Split Votes by Sikka, Ethermint, Cosmwasm)
- Incentive test net participants' compensation for function improvement (Gravity DEX)
- Protect privacy event and marketing(ZKValidator)
- Marketing(Cosmos Hub & Tendermint)
- Funding(Cosmos Governance Working Group)

## Detailed proposals.

[Rejected][ATOM 🤝 Osmosis: Allocate Community Pool to ATOM Liquidity Incentives](https://www.mintscan.io/cosmos/proposals/52): Cosmos Hub dedicate 100,000 ATOMs from its Community Pool to be allocated towards liquidity incentives on Osmosis over the next 3 months. 

[Passed][Community Fund Governance Proposal For Gravity DEX Incentivized Testnet Prize Pool](https://www.mintscan.io/cosmos/proposals/45): This governance proposal is to ask Atom delegators to allow the spending of 5,000 Atoms for the Gravity DEX Incentivized Testnet (Trading Competition) from the Cosmos Hub Community Fund. It seems to be used as a prize for the winner of the test net competition for Gravity DEX incentives.

[Passed][Advancing Ethermint: GTM and Engineering Plan for the Ethermint Chain](https://www.mintscan.io/cosmos/proposals/44): This governance proposal is 100,000 ATOMs from the Cosmos Hub community pool to fund, develop and advance the Ethermint project and launch an Ethermint Chain.

[Passed][ZKValidator Community Spend Proposal](https://www.mintscan.io/cosmos/proposals/42): The proposal is to spend 5k Atoms from the community pool and to deliver four quarterly privacy focussed events. Fund zkvalidator to support events to protect privacy.

[Passed][Luna Mission - Funding $ATOM](https://www.mintscan.io/cosmos/proposals/34): The Cosmos Hub (ATOM) community is requesting a community pool spend amount of 129,208 ATOM in order to implement a comprehensive ATOM marketing plan that will be executed in collaboration with AiB (Tendermint). 

[Passed][Funding for Development of Governance Split Votes](https://www.mintscan.io/cosmos/proposals/32): 
Sikka is requesting 1776 ATOMs from the community pool to architect and implement the Governance Split Votes feature proposed in Cosmos Hub Proposal #31. Provide funds to external developers for the development of functions passed by Cosmos Proposal.

[Rejected][Takeoff Proposal from Cyber to Cosmos](https://www.mintscan.io/cosmos/proposals/26): It's hard to understand that it seems to be an investment proposal.

[Passed][CosmWasm Integration 1 - Permissions and Upgrades](https://www.mintscan.io/cosmos/proposals/25): Reward for CosmWasm's function improvement.

[Passed][Cosmos Governance Working Group - Q1 2020](https://www.mintscan.io/cosmos/proposals/23): Proposal for financing to be used by Cosmos Governance Working Group

**Comment by gyuguen** [comment] 2021-09-27 07:17
## This is an explanation of how to add and use community taxes.

### Add community tax.
You need to register a parameter change proposal.
Community tax is 0% before this proposal is passed.
```shell
$ panacead q distribution params
base_proposer_reward: "0.010000000000000000"
bonus_proposer_reward: "0.040000000000000000"
community_tax: "0.000000000000000000"
withdraw_addr_enabled: true
```

* proposal.json
```json 
{
  "title": "Change parameter Community Tax 2%",
  "description": "Update community_tax",
  "changes": [
    {
      "subspace": "distribution",
      "key": "communitytax",
      "value": "0.020000000000000000"
    }
  ],
  "deposit": "500000000umed"
}
```

```shell
$ panacead tx gov submit-proposal param-change ./proposal.json --from {key or address} --chain-id {chain_id}
```

Once the proposal is passed, the community tax will be revised to 2%.
```shell
$ panacead q distribution params
base_proposer_reward: "0.010000000000000000"
bonus_proposer_reward: "0.040000000000000000"
community_tax: "0.020000000000000000"
withdraw_addr_enabled: true
```

Now 2% of the minted MEDs will move to the community pool.

Before becoming Mint, community pool inquiry results
```shell
$ panacead q distribution community-pool
pool:
- amount: "22907845500.320000000000000000"
  denom: umed
```

```
# panacea log
3:50PM INF minted coins from module account amount=13318569781umed from=mint module=x/bank
```

After Mint, community pool inquiry result
```shell
$ panacead q distribution community-pool
pool:
- amount: "23174216895.940000000000000000"
  denom: umed
```
```
# Minted * 0.02
13318569781 * 0.02 = 266371395.62
# (After minted) - (Before minted)
23174216895.94 - 22907845500.32 = 266371395.62
```

**Comment by gyuguen** [comment] 2021-09-27 07:54
## Explain how to use the community pool

Register the community-pool-spend proposal.

This is the account before the proposal was passed.
```shell
$ panacead q bank balances panacea1a6yrdxnchps05xd4jmd5dgunkcx4tgkgz4zwm3
balances: []
pagination:
  next_key: null
  total: "0"
```

proposal.json
```json
{
  "title": "Community Pool Spend",
  "description": "Pay me some MEDs!",
  "recipient": "panacea1a6yrdxnchps05xd4jmd5dgunkcx4tgkgz4zwm3",
  "amount": "100000000umed",
  "deposit": "500000000umed"
}
```

```shell
panacead tx gov submit-proposal community-pool-spend ./proposal.json \
--from {key or address} \
--chain-id {chain_id}
```

This is the account after the proposal has been passed.
The amount specified in the proposal has been withdrawn from the community pool.

```shell
$ panacead q bank balances panacea1a6yrdxnchps05xd4jmd5dgunkcx4tgkgz4zwm3
balances:
- amount: "100000000"
  denom: umed
pagination:
  next_key: null
  total: "0"
```

**Comment by gyuguen** [comment] 2021-09-27 07:57
I found about a known bug.
https://github.com/cosmos/governance/blob/master/params-change/Distribution.md#known-bug.

You can change the value while checking the specifications below. There is no problem with our changes.
```
[0] The value of communitytax must be positive and cannot exceed 1.00.
[1] baseproposerreward and bonusproposerreward must be positive and their sum cannot exceed 1.00.
```
https://github.com/cosmos/cosmos-sdk/blob/v0.42.9/x/distribution/spec/07_params.md

**Comment by gyuguen** [comment] 2021-09-27 08:06
## Min Proposal Deposit
How to apply this change is not very difficult.
This proposal will be included with the change in community tax.

proposal.json
```json
{
  "title": "Gov Param Change",
  "description": "Update min_deposit",
  "changes": [
    {
      "subspace": "gov",
      "key": "depositparams",
      "value": {
        "min_deposit": [
          {
            "denom": "umed",
            "amount": "10000000000"
          }
        ]
      }
    }
  ],
  "deposit": "500000000umed"
}
```

**Comment by youngjoon-lee** [comment] 2021-09-28 04:22
Thank you. It seems that we don't need to change any other parameters except community_tax and min_deposit as you described above.

**Comment by gyuguen** [comment] 2021-09-28 04:24
Yes, that's right. I don't think we need to change anything else.

**Comment by gyuguen** [comment] 2021-09-28 08:40
I posted a proposal on devnet and confirmed that it works without any problems.

https://devnet-explorer.gopanacea.org/proposals/3

![스크린샷 2021-09-28 오후 5 36 22](https://user-images.githubusercontent.com/10514738/135053338-a922d4bc-21ca-44fb-8e69-1ebdd248342e.png)

**Comment by youngjoon-lee** [comment] 2021-09-28 08:47
Great. Thanks!

**Comment by gyuguen** [comment] 2021-11-26 05:22
This has been applied to the mainnet, so we close it.

**Closed by gyuguen** 2021-11-26 05:22 UTC
Labels: discussion
